version: "3.8"

services:
  hugo:
    build:
      context: infra/hugo
      args:
        - HUGO_BUILD_TAGS=extended
    volumes:
      - ./:/site
    working_dir: /site/src
    ports:
      - ${HUGO_SERVER_PORT}:${HUGO_SERVER_PORT}
    command: server --bind 0.0.0.0 --port ${HUGO_SERVER_PORT}
